version: "3.4"

volumes:
  trueblocksdnpdappnodeeth_data: {}

services:
  trueblocks.public.dappnode.eth:
    build: .
    image: trueblocks.public.dappnode.eth:0.0.1
    container_name: DAppNodePackage-trueblocks.dnp.dappnode.eth
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - trueblocksdnpdappnodeeth_data:/root/.quickBlocks
    ports:
      - 80:80
    env_file:
      - trueblocks.public.dappnode.eth.env
